import { Component, signal } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { provideHttpClient, HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root', standalone: true, imports: [FormsModule],
  template: `
    @if (!token()) {
      <main class="login-shell"><section class="login-card"><span class="eyebrow">DAERTECH</span><h1>Infrastructure Management Platform</h1><p>Acceso administrativo seguro.</p>
        <form (ngSubmit)="login()"><label>Usuario<input [(ngModel)]="username" name="username" required></label><label>Contraseña<input [(ngModel)]="password" name="password" type="password" required></label><button [disabled]="loading()">{{loading()?'Validando…':'Iniciar sesión'}}</button>@if(error()){<p class="error">{{error()}}</p>}</form>
      </section></main>
    } @else {
      <main class="shell"><header><div><span class="eyebrow">DAERTECH</span><h1>Centro de administración</h1><p>Seguridad, configuración, aplicaciones, despliegues y auditoría.</p></div><button class="secondary" (click)="logout()">Cerrar sesión</button></header>
        <nav><button (click)="section.set('dashboard')">Dashboard</button><button (click)="loadUsers()">Usuarios</button><button (click)="loadRoles()">Roles</button><button (click)="loadPermissions()">Permisos</button><button (click)="openConfig()">Configuración</button><button (click)="openApplications()">Aplicaciones</button><button (click)="openDeployments()">Despliegues</button></nav>
        @if(error()){<div class="banner error">{{error()}} <button class="link" (click)="error.set('')">Cerrar</button></div>}
        @if(section()==='dashboard'){
          <section class="grid">@for(item of modules;track item.name){<article><h2>{{item.name}}</h2><p>{{item.description}}</p><span>{{item.state}}</span></article>}</section>
        } @else if(section()==='deployments') {
          <section class="panel"><div class="panel-head"><div><h2>Deployment Center</h2><p>Solicitudes, ejecución, health checks, rollback, promoción, registry y blue/green.</p></div><div class="actions"><select [(ngModel)]="deploymentEnvironment" (change)="loadDeployments()"><option value="">Todos</option>@for(env of environments;track env){<option [value]="env">{{env}}</option>}</select><button (click)="loadDeployments()">Actualizar</button></div></div>
            <form class="config-form" (ngSubmit)="createDeployment()">
              <label>Aplicación<select [(ngModel)]="deployment.applicationId" name="deploymentApplication" required><option value="">Seleccione</option>@for(app of applications();track app.id){<option [value]="app.id">{{app.code}} — {{app.name}}</option>}</select></label>
              <label>Ambiente<select [(ngModel)]="deployment.environment" name="deploymentEnvironment" required>@for(env of environments;track env){<option [value]="env">{{env}}</option>}</select></label>
              <label>Versión<input [(ngModel)]="deployment.version" name="deploymentVersion" placeholder="1.0.0" required></label><label>Rama<input [(ngModel)]="deployment.branch" name="deploymentBranch" placeholder="main"></label>
              <label>Motivo<input [(ngModel)]="deployment.reason" name="deploymentReason" required></label><button [disabled]="operationBusy()">Crear solicitud</button>
            </form>
            <div class="table-wrap"><table><thead><tr><th>Aplicación</th><th>Ambiente</th><th>Versión</th><th>Estrategia</th><th>Estado</th><th>Health</th><th>Slot</th><th>Solicitado</th></tr></thead><tbody>@for(row of deployments();track row.id){<tr class="clickable" (click)="selectDeployment(row.id)"><td>{{row.application_code}}</td><td>{{row.environment}}</td><td>{{row.version}}</td><td>{{row.strategy||'RECREATE'}}</td><td><span class="status" [class.ok-bg]="row.status==='SUCCESS'" [class.error-bg]="row.status==='FAILED'">{{row.status}}</span></td><td>{{row.health_status||'—'}}</td><td>{{row.active_slot||'—'}}</td><td>{{row.requested_by}}</td></tr>}</tbody></table></div>
            @if(selectedDeployment()){
              <section class="detail-card"><div class="panel-head"><div><h3>{{selectedDeployment().application_code}} · {{selectedDeployment().environment}} · {{selectedDeployment().version}}</h3><p>ID: {{selectedDeployment().id}}</p></div><div class="actions"><button (click)="executeDeployment()" [disabled]="operationBusy()">Ejecutar</button><button class="secondary" (click)="rollbackDeployment()" [disabled]="operationBusy()">Rollback</button><button class="secondary" (click)="pushImage()" [disabled]="operationBusy()">Publicar imagen</button></div></div>
                <div class="summary-grid"><div><b>Estado</b><span>{{selectedDeployment().status}}</span></div><div><b>Commit</b><span>{{selectedDeployment().git_commit||'—'}}</span></div><div><b>Imagen local</b><span>{{selectedDeployment().image_tag||'—'}}</span></div><div><b>Imagen registry</b><span>{{selectedDeployment().registry_image||'—'}}</span></div><div><b>Health</b><span>{{selectedDeployment().health_message||'—'}}</span></div><div><b>Notificación</b><span>{{selectedDeployment().notification_status||'—'}}</span></div></div>
                <div class="runtime-bar"><label>Estrategia<select [(ngModel)]="strategy.strategy">@for(item of strategies;track item){<option [value]="item">{{item}}</option>}</select></label><label>Imagen registry<input [(ngModel)]="strategy.registryImage" placeholder="registry/imagen:tag"></label><button (click)="saveStrategy()" [disabled]="operationBusy()">Guardar estrategia</button><label>Promover a<select [(ngModel)]="promotion.targetEnvironment">@for(env of environments;track env){<option [value]="env">{{env}}</option>}</select></label><button (click)="promoteDeployment()" [disabled]="operationBusy()">Promover</button><button class="blue" (click)="switchTraffic('BLUE')" [disabled]="operationBusy()">Activar BLUE</button><button class="green" (click)="switchTraffic('GREEN')" [disabled]="operationBusy()">Activar GREEN</button></div>
                <h3>Pasos</h3><div class="table-wrap"><table><thead><tr><th>#</th><th>Paso</th><th>Estado</th><th>Código</th><th>Salida</th></tr></thead><tbody>@for(step of selectedDeployment().steps||[];track step.id){<tr><td>{{step.step_order}}</td><td>{{step.step_name}}</td><td>{{step.status}}</td><td>{{step.exit_code??'—'}}</td><td><pre>{{step.output||'—'}}</pre></td></tr>}</tbody></table></div>
                <h3>Eventos runtime</h3><div class="table-wrap"><table><thead><tr><th>Evento</th><th>Estado</th><th>Usuario</th><th>Detalle</th><th>Fecha</th></tr></thead><tbody>@for(event of runtimeEvents();track event.id){<tr><td>{{event.event_type}}</td><td>{{event.status}}</td><td>{{event.performed_by}}</td><td><pre>{{event.details}}</pre></td><td>{{event.created_at}}</td></tr>}</tbody></table></div>
              </section>
            }
          </section>
        } @else if(section()==='applications') {
          <section class="panel"><div class="panel-head"><div><h2>Applications Center</h2><p>Catálogo técnico de aplicaciones, repositorios, ramas, puertos y endpoints operativos.</p></div></div>
            <form class="config-form" (ngSubmit)="saveApplication()"><label>Código<input [(ngModel)]="application.code" name="appCode" required></label><label>Nombre<input [(ngModel)]="application.name" name="appName" required></label><label>Repositorio Git<input [(ngModel)]="application.repositoryUrl" name="repositoryUrl" required></label><label>Rama<input [(ngModel)]="application.defaultBranch" name="defaultBranch"></label><label>Tecnología<select [(ngModel)]="application.technology" name="technology">@for(type of technologies;track type){<option [value]="type">{{type}}</option>}</select></label><label>Build tool<input [(ngModel)]="application.buildTool" name="buildTool"></label><label>Dockerfile<input [(ngModel)]="application.dockerfilePath" name="dockerfilePath"></label><label>Puerto interno<input [(ngModel)]="application.internalPort" name="internalPort" type="number"></label><label>Health path<input [(ngModel)]="application.healthPath" name="healthPath"></label><label>Metrics path<input [(ngModel)]="application.metricsPath" name="metricsPath"></label><label>Descripción<input [(ngModel)]="application.description" name="appDescription"></label><label class="check"><input type="checkbox" [(ngModel)]="application.active" name="appActive"> Activa</label><button>Guardar aplicación</button></form>
            <div class="table-wrap"><table><thead><tr><th>Código</th><th>Nombre</th><th>Tecnología</th><th>Rama</th><th>Puerto</th><th>Health</th><th>Activa</th></tr></thead><tbody>@for(row of applications();track row.id){<tr class="clickable" (click)="selectApplication(row)"><td>{{row.code}}</td><td>{{row.name}}</td><td>{{row.technology}}</td><td>{{row.default_branch}}</td><td>{{row.internal_port||'—'}}</td><td>{{row.health_path||'—'}}</td><td>{{row.active?'Sí':'No'}}</td></tr>}</tbody></table></div>
          </section>
        } @else if(section()==='config') {
          <section class="panel"><div class="panel-head"><div><h2>Configuration Center</h2><p>Valores por ambiente con secretos cifrados, historial y exportación.</p></div><div class="actions"><select [(ngModel)]="configEnvironment" (change)="loadConfigurations()">@for(env of environments;track env){<option [value]="env">{{env}}</option>}</select><button (click)="download('ENV')">Exportar .env</button><button (click)="download('YAML')">Exportar YAML</button></div></div>
            <form class="config-form" (ngSubmit)="saveConfiguration()"><label>Categoría<input [(ngModel)]="config.category" name="category" required></label><label>Clave<input [(ngModel)]="config.key" name="key" required></label><label>Tipo<select [(ngModel)]="config.valueType" name="valueType">@for(type of valueTypes;track type){<option [value]="type">{{type}}</option>}</select></label><label>Valor<input [(ngModel)]="config.value" name="value" [type]="config.secret?'password':'text'" required></label><label>Descripción<input [(ngModel)]="config.description" name="description"></label><label>Validación regex<input [(ngModel)]="config.validationRule" name="validationRule"></label><label class="check"><input type="checkbox" [(ngModel)]="config.secret" name="secret"> Secreto</label><label class="check"><input type="checkbox" [(ngModel)]="config.active" name="active"> Activo</label><label>Motivo<input [(ngModel)]="config.reason" name="reason" required></label><button>Guardar configuración</button></form>
            <div class="validator"><h3>Probar conectividad</h3><div class="inline"><select [(ngModel)]="validation.type">@for(type of validationTypes;track type){<option [value]="type">{{type}}</option>}</select><input [(ngModel)]="validation.host" placeholder="host o dominio"><input [(ngModel)]="validation.port" type="number" placeholder="puerto"><input [(ngModel)]="validation.path" placeholder="/health"><button (click)="validateConnection()">Validar</button></div>@if(validationResult()){<p [class.ok]="validationResult().success" [class.error]="!validationResult().success">{{validationResult().message}} · {{validationResult().elapsedMs}} ms</p>}</div>
            <div class="table-wrap"><table><thead><tr><th>Categoría</th><th>Clave</th><th>Valor</th><th>Tipo</th><th>Secreto</th><th>Versión</th></tr></thead><tbody>@for(row of configurations();track row.id){<tr><td>{{row.category}}</td><td>{{row.key}}</td><td>{{row.value}}</td><td>{{row.valueType}}</td><td>{{row.secret?'Sí':'No'}}</td><td>{{row.version}}</td></tr>}</tbody></table></div>
          </section>
        } @else {
          <section class="panel"><h2>{{title()}}</h2><div class="table-wrap"><table><thead><tr>@for(column of columns();track column){<th>{{column}}</th>}</tr></thead><tbody>@for(row of rows();track row.id){<tr>@for(column of columns();track column){<td>{{row[key(column)]??'—'}}</td>}</tr>}</tbody></table></div></section>
        }
      </main>
    }
  `
})
class AppComponent {
  private readonly api='/api/v1'; token=signal(localStorage.getItem('accessToken')); loading=signal(false); operationBusy=signal(false); error=signal(''); section=signal('dashboard'); title=signal(''); rows=signal<any[]>([]); columns=signal<string[]>([]); configurations=signal<any[]>([]); applications=signal<any[]>([]); deployments=signal<any[]>([]); selectedDeployment=signal<any>(null); runtimeEvents=signal<any[]>([]); validationResult=signal<any>(null);
  username='admin'; password=''; configEnvironment='PRODUCTION'; deploymentEnvironment=''; environments=['DEVELOPMENT','QA','CERTIFICATION','PRODUCTION']; strategies=['RECREATE','ROLLING','BLUE_GREEN']; valueTypes=['STRING','NUMBER','BOOLEAN','URL','JSON','PASSWORD','TOKEN','CERTIFICATE']; validationTypes=['HTTP','HTTPS','TCP','POSTGRESQL','MYSQL','REDIS','RABBITMQ','MQTT','SMTP','MINIO','REST','SOAP','TELEGRAM']; technologies=['ANGULAR','SPRING_BOOT','NODEJS','PHP','GO','PYTHON','DOTNET','ORACLE_FORMS','STATIC','OTHER'];
  config:any={category:'GENERAL',key:'',value:'',secret:false,environment:'PRODUCTION',valueType:'STRING',description:'',validationRule:'',active:true,reason:'Configuración inicial'}; validation:any={type:'HTTP',host:'localhost',port:8080,path:'/api/v1/actuator/health',scheme:'http',method:'GET',timeoutMs:5000};
  application:any={id:null,code:'',name:'',description:'',repositoryUrl:'',defaultBranch:'main',technology:'SPRING_BOOT',buildTool:'Maven',dockerfilePath:'Dockerfile',contextPath:'.',internalPort:8080,healthPath:'/actuator/health',metricsPath:'/actuator/prometheus',active:true};
  deployment:any={applicationId:'',environment:'DEVELOPMENT',version:'',branch:'main',reason:'Despliegue solicitado desde la plataforma'}; strategy:any={strategy:'RECREATE',registryId:null,registryImage:''}; promotion:any={targetEnvironment:'QA',reason:'Promoción aprobada'};
  readonly modules=[{name:'Seguridad',description:'Usuarios, roles, permisos y sesiones.',state:'Funcional'},{name:'Configuración',description:'Ambientes, secretos, validación, historial y exportación.',state:'Funcional'},{name:'Aplicaciones',description:'Registro, versiones, variables y dependencias.',state:'Funcional'},{name:'Despliegues',description:'Build, publicación, health check, promoción y rollback.',state:'Funcional'},{name:'Monitoreo',description:'Prometheus, Grafana, Loki y Alertmanager.',state:'Siguiente fase'},{name:'Auditoría',description:'Trazabilidad de cambios y accesos.',state:'Automática'}];
  constructor(private http:HttpClient){}
  login(){this.loading.set(true);this.error.set('');this.http.post<any>(`${this.api}/auth/login`,{username:this.username,password:this.password}).subscribe({next:r=>{localStorage.setItem('accessToken',r.accessToken);localStorage.setItem('refreshToken',r.refreshToken);this.token.set(r.accessToken);this.loading.set(false)},error:e=>{this.error.set(e?.error?.message||'Credenciales inválidas');this.loading.set(false)}})}
  logout(){const refreshToken=localStorage.getItem('refreshToken');this.http.post(`${this.api}/auth/logout`,{refreshToken}).subscribe({complete:()=>this.clear(),error:()=>this.clear()})} clear(){localStorage.clear();this.token.set(null);this.section.set('dashboard')} headers(){return{Authorization:`Bearer ${this.token()}`}}
  loadUsers(){this.load('users','Usuarios',['Usuario','Correo','Nombre','Habilitado','Bloqueado'])} loadRoles(){this.load('roles','Roles',['Código','Nombre','Descripción','Activo'])} loadPermissions(){this.load('permissions','Permisos',['Código','Nombre','Módulo'])}
  load(resource:string,title:string,columns:string[]){this.http.get<any[]>(`${this.api}/admin/${resource}`,{headers:this.headers()}).subscribe({next:data=>{this.rows.set(data);this.columns.set(columns);this.title.set(title);this.section.set(resource)},error:e=>this.handle(e)})}
  openApplications(){this.section.set('applications');this.loadApplications()} loadApplications(){this.http.get<any[]>(`${this.api}/admin/applications`,{headers:this.headers()}).subscribe({next:r=>this.applications.set(r),error:e=>this.handle(e)})}
  saveApplication(){const payload={...this.application,internalPort:this.application.internalPort?Number(this.application.internalPort):null};this.http.post<any>(`${this.api}/admin/applications`,payload,{headers:this.headers()}).subscribe({next:()=>{this.application={...this.application,id:null,code:'',name:'',description:'',repositoryUrl:''};this.loadApplications()},error:e=>this.handle(e)})}
  selectApplication(row:any){this.http.get<any>(`${this.api}/admin/applications/${row.id}`,{headers:this.headers()}).subscribe({next:r=>this.application={id:r.id,code:r.code,name:r.name,description:r.description,repositoryUrl:r.repository_url,defaultBranch:r.default_branch,technology:r.technology,buildTool:r.build_tool,dockerfilePath:r.dockerfile_path,contextPath:r.context_path,internalPort:r.internal_port,healthPath:r.health_path,metricsPath:r.metrics_path,active:r.active},error:e=>this.handle(e)})}
  openDeployments(){this.section.set('deployments');this.loadApplications();this.loadDeployments()}
  loadDeployments(){const query=this.deploymentEnvironment?`?environment=${this.deploymentEnvironment}`:'';this.http.get<any[]>(`${this.api}/admin/deployments${query}`,{headers:this.headers()}).subscribe({next:r=>this.deployments.set(r),error:e=>this.handle(e)})}
  createDeployment(){this.operationBusy.set(true);this.http.post<any>(`${this.api}/admin/deployments`,this.deployment,{headers:this.headers()}).subscribe({next:r=>{this.operationBusy.set(false);this.deployment={...this.deployment,version:'',reason:'Despliegue solicitado desde la plataforma'};this.loadDeployments();this.selectDeployment(r.id)},error:e=>this.handleOperation(e)})}
  selectDeployment(id:string){this.http.get<any>(`${this.api}/admin/deployments/${id}`,{headers:this.headers()}).subscribe({next:r=>{this.selectedDeployment.set(r);this.strategy={strategy:r.strategy||'RECREATE',registryId:r.registry_id||null,registryImage:r.registry_image||''};this.loadRuntimeEvents(id)},error:e=>this.handle(e)})}
  loadRuntimeEvents(id:string){this.http.get<any[]>(`${this.api}/admin/deployment-runtime/${id}/events`,{headers:this.headers()}).subscribe({next:r=>this.runtimeEvents.set(r),error:e=>this.handle(e)})}
  executeDeployment(){this.postAction(`${this.api}/admin/deployments/${this.selectedDeployment().id}/execute`,{},true)}
  rollbackDeployment(){this.postAction(`${this.api}/admin/deployments/${this.selectedDeployment().id}/rollback`,{reason:'Rollback solicitado desde la interfaz'},false)}
  pushImage(){this.postAction(`${this.api}/admin/deployment-runtime/${this.selectedDeployment().id}/push`,{},true)}
  switchTraffic(slot:string){this.postAction(`${this.api}/admin/deployment-runtime/${this.selectedDeployment().id}/switch-traffic`,{targetSlot:slot},true)}
  saveStrategy(){this.postAction(`${this.api}/admin/deployment-operations/${this.selectedDeployment().id}/strategy`,this.strategy,true)}
  promoteDeployment(){this.postAction(`${this.api}/admin/deployment-operations/${this.selectedDeployment().id}/promote`,this.promotion,false)}
  postAction(url:string,body:any,refreshCurrent:boolean){this.operationBusy.set(true);this.http.post<any>(url,body,{headers:this.headers()}).subscribe({next:r=>{this.operationBusy.set(false);this.loadDeployments();const id=refreshCurrent?this.selectedDeployment()?.id:r?.id;if(id)this.selectDeployment(id)},error:e=>this.handleOperation(e)})}
  openConfig(){this.section.set('config');this.loadConfigurations()} loadConfigurations(){this.http.get<any[]>(`${this.api}/admin/configurations?environment=${this.configEnvironment}`,{headers:this.headers()}).subscribe({next:r=>this.configurations.set(r),error:e=>this.handle(e)})}
  saveConfiguration(){this.config.environment=this.configEnvironment;this.config.key=this.config.key.toUpperCase();this.http.post<any>(`${this.api}/admin/configurations`,this.config,{headers:this.headers()}).subscribe({next:()=>{this.config={...this.config,key:'',value:'',reason:'Actualización administrativa'};this.loadConfigurations()},error:e=>this.handle(e)})}
  validateConnection(){const payload={...this.validation,port:this.validation.port?Number(this.validation.port):null};this.http.post<any>(`${this.api}/admin/configuration-operations/validate`,payload,{headers:this.headers()}).subscribe({next:r=>this.validationResult.set(r),error:e=>this.handle(e)})}
  download(format:string){this.http.get(`${this.api}/admin/configuration-operations/export?environment=${this.configEnvironment}&format=${format}`,{headers:this.headers(),responseType:'blob'}).subscribe({next:blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`daertech-${this.configEnvironment.toLowerCase()}.${format==='YAML'?'yaml':'env'}`;a.click();URL.revokeObjectURL(a.href)},error:e=>this.handle(e)})}
  handleOperation(e:any){this.operationBusy.set(false);this.handle(e)} handle(e:any){if(e.status===401)this.clear();else this.error.set(e?.error?.message||e?.error?.detail||'Operación no completada')} key(label:string){return({'Usuario':'username','Correo':'email','Nombre':'full_name','Habilitado':'enabled','Bloqueado':'locked','Código':'code','Descripción':'description','Activo':'active','Módulo':'module'}as any)[label]||label.toLowerCase()}
}
bootstrapApplication(AppComponent,{providers:[provideHttpClient()]}).catch(console.error);
