package com.daertech.platform.configuration;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.net.HttpURLConnection;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.URL;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.*;

@Service
public class ConfigurationOperationsService {
    private final ConfigurationRepository repository;
    private final SecretCipher cipher;
    private final JdbcTemplate jdbc;

    public ConfigurationOperationsService(ConfigurationRepository repository, SecretCipher cipher, JdbcTemplate jdbc) {
        this.repository = repository;
        this.cipher = cipher;
        this.jdbc = jdbc;
    }

    public Map<String,Object> validate(ValidationRequest request) {
        long started = System.currentTimeMillis();
        try {
            String type = request.type().toUpperCase(Locale.ROOT);
            return switch (type) {
                case "HTTP", "HTTPS", "REST", "SOAP", "TELEGRAM" -> validateHttp(request, started);
                case "TCP", "POSTGRESQL", "MYSQL", "REDIS", "RABBITMQ", "MQTT", "SMTP", "MINIO" -> validateTcp(request, started);
                default -> throw new IllegalArgumentException("Tipo de validación no soportado: " + type);
            };
        } catch (Exception ex) {
            return result(false, request.type(), request.host(), request.port(), System.currentTimeMillis() - started, ex.getMessage());
        }
    }

    public String export(String environment, String format, boolean includeSecrets) {
        var items = repository.findAllByEnvironmentOrderByCategoryAscKeyAsc(environment.toUpperCase(Locale.ROOT));
        if ("YAML".equalsIgnoreCase(format) || "YML".equalsIgnoreCase(format)) {
            StringBuilder out = new StringBuilder("environment: ").append(environment.toUpperCase(Locale.ROOT)).append('\n').append("configuration:\n");
            for (ConfigurationItem item : items) {
                out.append("  ").append(item.getKey()).append(": ").append(yamlValue(value(item, includeSecrets))).append('\n');
            }
            return out.toString();
        }
        StringBuilder out = new StringBuilder("# Generated by DAERTECH Platform\n# Environment: ").append(environment.toUpperCase(Locale.ROOT)).append("\n");
        for (ConfigurationItem item : items) {
            out.append(item.getKey()).append('=').append(envValue(value(item, includeSecrets))).append('\n');
        }
        return out.toString();
    }

    private String value(ConfigurationItem item, boolean includeSecrets) {
        if (!item.isSecret()) return item.getValue() == null ? "" : item.getValue();
        if (!includeSecrets) return "********";
        return item.getValue() == null ? "" : cipher.decrypt(item.getValue());
    }

    private Map<String,Object> validateHttp(ValidationRequest request, long started) throws Exception {
        String scheme = request.scheme() == null || request.scheme().isBlank() ? "http" : request.scheme();
        int port = request.port() == null ? ("https".equalsIgnoreCase(scheme) ? 443 : 80) : request.port();
        String path = request.path() == null || request.path().isBlank() ? "/" : request.path();
        URL url = URI.create(scheme + "://" + request.host() + ":" + port + path).toURL();
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setConnectTimeout(timeout(request));
        connection.setReadTimeout(timeout(request));
        connection.setRequestMethod(request.method() == null ? "GET" : request.method().toUpperCase(Locale.ROOT));
        if (request.headers() != null) request.headers().forEach(connection::setRequestProperty);
        int status = connection.getResponseCode();
        boolean ok = status >= 200 && status < 500;
        Map<String,Object> result = result(ok, request.type(), request.host(), port, System.currentTimeMillis() - started, "HTTP " + status);
        result.put("statusCode", status);
        return result;
    }

    private Map<String,Object> validateTcp(ValidationRequest request, long started) throws Exception {
        if (request.port() == null) throw new IllegalArgumentException("Puerto requerido");
        try (Socket socket = new Socket()) {
            socket.connect(new InetSocketAddress(request.host(), request.port()), timeout(request));
        }
        return result(true, request.type(), request.host(), request.port(), System.currentTimeMillis() - started, "Conexión TCP satisfactoria");
    }

    private int timeout(ValidationRequest request) {
        return request.timeoutMs() == null ? 5000 : Math.max(500, Math.min(request.timeoutMs(), 30000));
    }

    private Map<String,Object> result(boolean success, String type, String host, Integer port, long elapsed, String message) {
        Map<String,Object> value = new LinkedHashMap<>();
        value.put("success", success);
        value.put("type", type);
        value.put("host", host);
        value.put("port", port);
        value.put("elapsedMs", elapsed);
        value.put("message", message);
        return value;
    }

    private String envValue(String value) {
        if (value.matches("[A-Za-z0-9_./:@+-]*")) return value;
        return '"' + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + '"';
    }

    private String yamlValue(String value) {
        return '"' + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + '"';
    }

    public record ValidationRequest(String type, String scheme, String host, Integer port, String path, String method, Integer timeoutMs, Map<String,String> headers) {}
}
